name: myenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - setuptools=49.1.0
  - colcon-common-extensions
  - vcstool
  - rosdep
  - console_bridge
  - boost=1.69
  - tinyxml2
  - poco
  - bzip2
  - lz4-c
  - opencv=3
  - eigen
