name: myenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - cmake
  - colcon-common-extensions
  - colcon-ros=0.3.18
  - rosinstall_generator
  - vcstool
  - rosdep
  - console_bridge
  - boost=1.69
  - tinyxml2
  - poco
  - bzip2
  - lz4-c
  - opencv=3
  - eigen
